// src/components/Camera.tsx
import React, { FC } from 'react'
import { useRecoilValue } from 'recoil'
import { Box, Grid } from '@chakra-ui/react'

import { selectedPhonesDataState } from '@/utils/atoms'

import PhoneGrid from './PhoneGrid'
import Information from './Information'

const joinWithBr = (arr: string[]) => <>
  {
    arr.map(t => <>
      <span>{t}</span>
      <br/>
    </>
    )}
</>

const Camera: FC = () => {
  const phones = useRecoilValue(selectedPhonesDataState)
  return <Box>
    {
      <PhoneGrid>
        {
          phones.map((phone, index) => {
            return <Box key={index}>
              {
                phone ? <Grid gridRowGap={4}>
                  <Information name='전면 카메라' data={joinWithBr(phone.data.camera.front)} />
                  <Information name='후면 카메라' data={joinWithBr(phone.data.camera.back)} />
                </Grid>
                  : ''
              }
            </Box>
          }
          )}
      </PhoneGrid>
    }
  </Box>
}

export default Camera

// src/components/Camera.vue
<template>
  <div class="ui center aligned container">
    <h3>전면 카메라</h3>
    <p v-for="cam in phone.camera.front" :key="cam">
      {{cam}}
    </p>
    <h3>후면 카메라</h3>
    <p v-for="cam in phone.camera.back" :key="cam">
      {{cam}}
    </p>
  </div>

</template>

<script>
import { getData } from "../getPhone";
export default {
  name: "Camrea",
  props: {
    company: String,
    id: String
  },
  watch: {
    company: function() {
      this.$data.phone = getData(this.company, this.id);
    },
    id: function() {
      this.$data.phone = getData(this.company, this.id);
    }
  },
  data() {
    return {
      phone: getData(this.company, this.id)
    };
  }
};
</script>
